Trees
======
```{r}
exampleTree <-  
  list( "MAIN",
    list("SECOND","a", 
         list("2A","b",
              "c")
         ),
    list("THIRD", "d",
          list("2A","e", "f", "g") ),
    "h",
    list("FOURTH","i",
          list("4A","j","k","l"),
         "m" )
      )

displayTree <- function(tree) {
    treehelper <- function(tree, preface = "", mark = "", named = FALSE) {
        L <- length(tree)
        if (length(tree) > 0) {
            if (is.list(tree) | is.call(tree)) {
                cat(paste(preface, mark, "====>|", sep = ""))
                treehelper(tree[[1]], preface = "", named = named)  # keep it on the same line.
                # preface <- paste(preface,' |',sep='')

                if (L > 1) {
                  for (k in 2:L) {
                    cat(paste(preface, "     |\n", sep = ""))
                    treehelper(tree[[k]], named = named, mark = ifelse(k == 
                      L, "|", ""), preface = paste(preface, ifelse(k == L, "     ", 
                      "     |"), sep = ""))
                  }
                }
            } else {
                separator <- ifelse(named & tree == toupper(tree), "name:", 
                  "-> ")
                cat(paste(preface, mark, separator, tree, "\n", sep = ""))
            }
        }
    }
    # Now call treehelper on the tree
    if (inherits(tree, "formula")) {
        treehelper(tree[[-1]], named = FALSE)
        # [-1] is to skip the ~
    } else treehelper(tree, named = TRUE)
}

displayTree(exampleTree)
displayTree(~exp(-k*t)*sin(omega*t))
```
# Animal Tree
```{r}
animals <- list("Animals",list("Domesticated",list("Horse","Cat","Dog")),list("Wild",list("Lion","Tiger","Bear","Moose")),list("Non-Animals",list("Bailey")))

displayTree(animals)
```
# World Tree
```{r}
# Tree  of the World

ourTree <- list("The World",
  			list("Non-Continental", list("Fiji","New Zealand")),
				list("Continental",
               	  	  list("Africa", list("Ghana", "Kenya", "Morocco")),
                      list("Americas",
                      		list("North", list("Canada","Mexico")),
                            list("South",list("Chile","Bolivia"))),
                      list("Antarctica"),
                      list("Asia", 
                      		list("Thailand", "Bhutan", "Mongolia")),
                      list("Australia"),
					  list("Europe",
                    		list("Slovakia", "Romania"))))

displayTree(ourTree)
```