String Transformer Functions
===========================
## Reverser

`````{r}
Reverser <- function(x){
  Alpha <- strsplit(x,NULL)
  Beta <- rev(Alpha[[1]])
  return(paste(Beta, collapse=""))
}

Reverser2 <- function(x){
  Charlie <- strsplit(x,NULL)[[1]]
  Delta<-Charlie[rev(1:nchar(x))]
  paste(Delta, collapse="")
}
`````
Test statements:
`````{r}
# Put test statements here. Should return TRUE or FALSE
Reverser("dog")
Reverser2("dog")
`````
## Scrambler 
`````{r}
Scrambler <- function(x){
  Alpha <- strsplit(x,NULL)
  Beta <- sample(Alpha[[1]])
  return(paste(Beta, collapse=""))
}
``````
Test Statements:
`````{r}
Scrambler("Tom Wakin")
`````
## VowelBleeper
`````{r}
Bleeper <- function(x){
  gsub("[aeiou]","*",x)
}
`````
Test Statements:
`````{r}
Bleeper("Is this working")
`````
## L33T
`````{r}
l33t <- function(words){
  First <- gsub("[Ee]","3",words)
  Second <- gsub("[Aa]","4",First)
  Third <- gsub("[Oo]","0",Second)
  Fourth <- gsub("[Ll]","1",Third)
  gsub("[Ss]","5",Fourth)
}
`````
Test Statements
`````{r}
l33t("I really like dogs because they are adorable")
`````