Numbers and Strings
=====================
## Basic Statistics
```{r}
outlier <- function(x){
    qs <- quantile(x,probs=c(0.25,0.75))
    width <- 1.5*(qs[2]-qs[1])
    top <- width + qs[2]
    bottom <- qs[1] - width
    x[(x<bottom)|(x>top)]
}

outlier(5)
```
## Numbers and Languages
```{r}
EnglishNumbers <- c("zero","one","two","three","four","five","six","seven","eight","nine")

digitToWord <- function(n,language){
     return(language[n+1])
 }

digitToWord(4,EnglishNumbers)
`````````````
## Help for Crossword Puzzles
```{r}
lettersMatch <- function(words,pattern){
  words <- readLines(url("http://dtkaplan.github.io/ScientificComputing/Syllabus/Daily/Day-07/word_list_moby_crossword-flat/word_list_moby_crossword.flat.txt"))
  analyze <- grepl(pattern,words)
  return(words[analyze])
}
# 7 letter words starting with "b" ending in "ing"
lettersMatch(words,"^b...ing")
```
## Have your pi two ways
```{r}
piSeries <- function(n){
  state <- 0
  for(k in 1:(length(n))){
    result <- ((-1)^(k+1))/(2*k-1)
    state <- state + result
  }
  return(state*4)
}

piSeries(1:10000)
```

